name: 'shopstream'
version: '1.0.0'

profile: 'shopstream'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

on-run-end:
  - "{{ log('dbt run completed at ' ~ run_started_at, info=true) }}"

models:
  shopstream:
    staging:
      +materialized: view
      +schema: staging
      +tags: ['hourly']
    intermediate:
      +materialized: table
      +schema: intermediate
      +tags: ['daily']
      +post-hook: "ANALYZE {{ this }}"
    marts:
      +materialized: table
      +schema: marts
      +tags: ['daily']
      +post-hook:
        - "ANALYZE {{ this }}"
    vault:
      +schema: vault
      +tags: ['daily']
      raw:
        +materialized: incremental
        
